apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: task4
  name: task4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: task4
        access: external
    spec:
      containers:
      - image: httpd:2.4
        name: httpd
        ports:
        - containerPort: 80
        resources: 
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
